/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vnpljoohwubpuouhxnjb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZucGxqb29od3VicHVvdWh4bmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNjQ1MzcsImV4cCI6MjA4NTY0MDUzN30.mbMbz-uJ-tgScNWn14ZR1ozcscc1r6Z7qj1mJ9npqhk"